"""RaUP data models.

Plain structures (dataclasses), no persistence logic: that lives in
`raup.repository`. Field names mirror the Supabase schema (see
supabase/schema.sql), which is kept in Spanish intentionally — it's already
live infrastructure, not a Python identifier (see DECISIONS.md D-013).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _new_id() -> str:
    return str(uuid.uuid4())


class ConsultationMode(str, Enum):
    FIRST_VISIT = "primera_consulta"
    FOLLOW_UP = "seguimiento"


class SessionStatus(str, Enum):
    CREATED = "creada"
    IN_PROGRESS = "en_curso"
    COMPLETED = "completada"


# Free text on purpose, not a closed enum: the pilot is nutrition-focused,
# but the clinician can type any other specialty (see DECISIONS.md, Step 5).
DEFAULT_SPECIALTY = "Nutrición"


@dataclass
class Session:
    """A session = a pre-visit questionnaire generated by the clinician."""

    code: str
    mode: ConsultationMode
    specialty: str = DEFAULT_SPECIALTY
    consultation_reason: Optional[str] = None
    status: SessionStatus = SessionStatus.CREATED
    id: str = field(default_factory=_new_id)
    created_at: datetime = field(default_factory=_now)
    completed_at: Optional[datetime] = None


@dataclass
class Answer:
    """One question/answer pair from the adaptive questionnaire, in order."""

    session_id: str
    order: int
    question: str
    answer: str
    id: str = field(default_factory=_new_id)
    created_at: datetime = field(default_factory=_now)


@dataclass
class DocumentMetadata:
    """Metadata for a document uploaded by the patient.

    The file content itself lives in Supabase Storage (bucket "documentos");
    only the reference is stored here. The document is never read or
    processed (out of scope for the MVP).
    """

    session_id: str
    file_name: str
    storage_path: str
    mime_type: Optional[str] = None
    size_bytes: Optional[int] = None
    id: str = field(default_factory=_new_id)
    uploaded_at: datetime = field(default_factory=_now)


@dataclass
class Alert:
    """A warning signal triggered by a deterministic threshold (see D-009).

    `source` references the validated instrument that generated it (e.g.
    "PHQ-9"), never a free-form clinical judgement from the LLM.
    """

    code: str
    message: str
    source: str


@dataclass
class Report:
    """The output for the clinician. Never contains a diagnosis or a
    treatment (see CLAUDE.md, MDR Class I regulatory restriction)."""

    session_id: str
    executive_summary: str
    alerts: list[Alert] = field(default_factory=list)
    areas_to_explore: list[str] = field(default_factory=list)
    id: str = field(default_factory=_new_id)
    generated_at: datetime = field(default_factory=_now)
